# Generated by Django 5.1 on 2024-09-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True, max_length=200)),
                ('category', models.CharField(choices=[('food', 'food'), ('travel', 'travel'), ('health', 'health'), ('others', 'others')], default='others', max_length=200)),
                ('status', models.CharField(choices=[('others', 'others'), ('in-progress', 'in-progress'), ('done', 'done')], default='travel', max_length=200)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
