# Generated by Django 5.1 on 2024-09-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_expense_created_date_alter_expense_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
