# Generated by Django 5.1 on 2024-09-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_expense_updated_date_alter_expense_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'food'), ('travel', 'travel'), ('health', 'health'), ('others', 'others')], max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('others', 'others'), ('in-progress', 'in-progress'), ('done', 'done')], max_length=200),
        ),
    ]
