# Generated by Django 5.1 on 2024-09-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_expense_category_alter_expense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
